### PR TITLE
fix: update tooltip to follow shadcn/ui

### PR DESCRIPTION
**Pull request by mcquenji**
The current tooltip implementation doesn't match the design from shadcn.

| Shadcn UI Tooltip | Shadcn Flutter Tooltip |
|-------------------|------------------------|
| image | image |

This PR fixes this:
image

### CODE REVIEW

**Comment by sunarya-thito** [comment]
This package follows the New York style, not the default style. So, it already follows the shading/UI design system.
image

**Comment by mcquenji** [comment]
oh okay, is a style flag planned?

**Comment by sunarya-thito** [comment]
yes, when #18 is completed

**Comment by mcquenji** [comment]
okidoki, do you need any help?

**Comment by sunarya-thito** [comment]
> okidoki, do you need any help?

yes, many widgets does not have custom styling at the moment, you can pick a component and create a component theme data.
I don't really have specific guidelines for this, but `tracker.dart` has some examples
Defining theme data: https://github.com/sunarya-thito/shadcn_flutter/blob/master/lib/src/components/chart/tracker.dart#L84-L106
Accessing theme data: https://github.com/sunarya-thito/shadcn_flutter/blob/master/lib/src/components/chart/tracker.dart#L133

**Comment by mcquenji** [comment]
could you open some issues for the missing component's theme data and assign me?

**Comment by sunarya-thito** [comment]
> could you open some issues for the missing components' theme data and assign me?

Here #98, I cannot assign you on GitHub because it can only assign contribs, but once I merge your PR I think it will allow me to assign you for the next issues

**Comment by mcquenji** [comment]
closing in favor of #115

**Pull request closed without merging**
