### PR TITLE
Update switch.dart

### PR DESCRIPTION
**Pull request by KushagraVasal**
Switch crash my android app this change fixed it.

### CODE REVIEW

**Comment by sunarya-thito** [comment]
I'm curious how the focus border width causes the crash and why changing it to 1.6 fixes the issue? What kind of crash is happening on your device?

**Comment by KushagraVasal** [comment]
I am getting the following errors
`════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Container(padding: EdgeInsets.all(2.7), bg: BoxDecoration(color: Color(0xfffafafa), border: Border.all(BorderSide(color: Color(0x00fafafa), width: 2.7, strokeAlign: 3.8)), borderRadius: BorderRadius.circular(17.5)), constraints: BoxConstraints(w=45.0, h=25.1)):
'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 112 pos 15: 'padding.isNonNegative': is not true.`


`════════ Exception caught by rendering library ═════════════════════════════════
A RenderFlex overflowed by 99818 pixels on the right.`

`════════ Exception caught by rendering library ═════════════════════════════════
A RenderFlex overflowed by 99323 pixels on the bottom.`

**Comment by KushagraVasal** [comment]
I am using Flutter 3.24.1 and Dart 3.5.1
You can recreate the error by
creating flutter helloworld add shadcn_flutter switch
open in android emulator but for some reason error disappears in Chrome browser and linux - desktop

**Comment by KushagraVasal** [comment]
Screenshot_20241006_214951

**Comment by sunarya-thito** [comment]
I think the focus border width is not the issue here but rather I made an error with the focus border's strokeAlign that is scaled, which shouldn't be. You can try to remove the strokeAlign scaling and see that it wont make any error.

**Comment by KushagraVasal** [comment]
You are right
but a little bit of strokeAlign is required
after that, the switch circle became too small to fix that I removed the padding

**Comment by KushagraVasal** [comment]
Screenshot_20241007_184657
Screenshot_20241007_184743
left: shadcn_flutter
right: ui.shadcn.com

**Comment by sunarya-thito** [comment]
I'll check this out

**Comment by sunarya-thito** [comment]
Had it tested yesterday, the error still occurs with >=3x scaling

**Review by sunarya-thito — APPROVED** [review]

**Pull request merged**
